enhancement:
- all:
  - changed-files:
    - all-globs-to-all-files:
      - '**'
  - base-branch: main
needs docs:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - README.md
      - .github/*.md
  - base-branch: main
tests:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/testinfo.yml
  - base-branch: main
baklava:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Baklava.*
      - archive/*/*/baklava.*
  - base-branch: main
base64 encode decode:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Base64EncodeDecode.*
      - archive/*/*/base64-encode-decode.*
      - archive/*/*/base64EncodeDecode.*
      - archive/*/*/base64_encode_decode.*
  - base-branch: main
binary search:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/BinarySearch.*
      - archive/*/*/binary-search.*
      - archive/*/*/binarySearch.*
      - archive/*/*/binary_search.*
  - base-branch: main
bubble sort:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/BubbleSort.*
      - archive/*/*/bubble-sort.*
      - archive/*/*/bubbleSort.*
      - archive/*/*/bubble_sort.*
  - base-branch: main
capitalize:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Capitalize.*
      - archive/*/*/capitalize.*
  - base-branch: main
convex hull:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/ConvexHull.*
      - archive/*/*/convex-hull.*
      - archive/*/*/convexHull.*
      - archive/*/*/convex_hull.*
  - base-branch: main
depth first search:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/DepthFirstSearch.*
      - archive/*/*/depth-first-search.*
      - archive/*/*/depthFirstSearch.*
      - archive/*/*/depth_first_search.*
  - base-branch: main
dijkstra:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Dijkstra.*
      - archive/*/*/dijkstra.*
  - base-branch: main
duplicate character counter:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/DuplicateCharacterCounter.*
      - archive/*/*/duplicate-character-counter.*
      - archive/*/*/duplicateCharacterCounter.*
      - archive/*/*/duplicate_character_counter.*
  - base-branch: main
even odd:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/EvenOdd.*
      - archive/*/*/even-odd.*
      - archive/*/*/evenOdd.*
      - archive/*/*/even_odd.*
  - base-branch: main
factorial:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Factorial.*
      - archive/*/*/factorial.*
  - base-branch: main
fibonacci:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Fibonacci.*
      - archive/*/*/fibonacci.*
  - base-branch: main
file input output:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/FileInputOutput.*
      - archive/*/*/file-input-output.*
      - archive/*/*/fileInputOutput.*
      - archive/*/*/file_input_output.*
  - base-branch: main
fizz buzz:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/FizzBuzz.*
      - archive/*/*/fizz-buzz.*
      - archive/*/*/fizzBuzz.*
      - archive/*/*/fizz_buzz.*
  - base-branch: main
fraction math:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/FractionMath.*
      - archive/*/*/fraction-math.*
      - archive/*/*/fractionMath.*
      - archive/*/*/fraction_math.*
  - base-branch: main
hello world:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/HelloWorld.*
      - archive/*/*/hello-world.*
      - archive/*/*/helloWorld.*
      - archive/*/*/hello_world.*
  - base-branch: main
insertion sort:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/InsertionSort.*
      - archive/*/*/insertion-sort.*
      - archive/*/*/insertionSort.*
      - archive/*/*/insertion_sort.*
  - base-branch: main
job sequencing:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/JobSequencing.*
      - archive/*/*/job-sequencing.*
      - archive/*/*/jobSequencing.*
      - archive/*/*/job_sequencing.*
  - base-branch: main
josephus problem:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/JosephusProblem.*
      - archive/*/*/josephus-problem.*
      - archive/*/*/josephusProblem.*
      - archive/*/*/josephus_problem.*
  - base-branch: main
linear search:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/LinearSearch.*
      - archive/*/*/linear-search.*
      - archive/*/*/linearSearch.*
      - archive/*/*/linear_search.*
  - base-branch: main
longest common subsequence:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/LongestCommonSubsequence.*
      - archive/*/*/longest-common-subsequence.*
      - archive/*/*/longestCommonSubsequence.*
      - archive/*/*/longest_common_subsequence.*
  - base-branch: main
longest palindromic substring:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/LongestPalindromicSubstring.*
      - archive/*/*/longest-palindromic-substring.*
      - archive/*/*/longestPalindromicSubstring.*
      - archive/*/*/longest_palindromic_substring.*
  - base-branch: main
longest word:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/LongestWord.*
      - archive/*/*/longest-word.*
      - archive/*/*/longestWord.*
      - archive/*/*/longest_word.*
  - base-branch: main
maximum array rotation:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/MaximumArrayRotation.*
      - archive/*/*/maximum-array-rotation.*
      - archive/*/*/maximumArrayRotation.*
      - archive/*/*/maximum_array_rotation.*
  - base-branch: main
maximum subarray:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/MaximumSubarray.*
      - archive/*/*/maximum-subarray.*
      - archive/*/*/maximumSubarray.*
      - archive/*/*/maximum_subarray.*
  - base-branch: main
merge sort:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/MergeSort.*
      - archive/*/*/merge-sort.*
      - archive/*/*/mergeSort.*
      - archive/*/*/merge_sort.*
  - base-branch: main
minimum spanning tree:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/MinimumSpanningTree.*
      - archive/*/*/minimum-spanning-tree.*
      - archive/*/*/minimumSpanningTree.*
      - archive/*/*/minimum_spanning_tree.*
  - base-branch: main
palindromic number:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/PalindromicNumber.*
      - archive/*/*/palindromic-number.*
      - archive/*/*/palindromicNumber.*
      - archive/*/*/palindromic_number.*
  - base-branch: main
prime number:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/PrimeNumber.*
      - archive/*/*/prime-number.*
      - archive/*/*/primeNumber.*
      - archive/*/*/prime_number.*
  - base-branch: main
quick sort:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/QuickSort.*
      - archive/*/*/quick-sort.*
      - archive/*/*/quickSort.*
      - archive/*/*/quick_sort.*
  - base-branch: main
quine:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Quine.*
      - archive/*/*/quine.*
  - base-branch: main
remove all whitespace:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/RemoveAllWhitespace.*
      - archive/*/*/remove-all-whitespace.*
      - archive/*/*/removeAllWhitespace.*
      - archive/*/*/remove_all_whitespace.*
  - base-branch: main
reverse string:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/ReverseString.*
      - archive/*/*/reverse-string.*
      - archive/*/*/reverseString.*
      - archive/*/*/reverse_string.*
  - base-branch: main
roman numeral:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/RomanNumeral.*
      - archive/*/*/roman-numeral.*
      - archive/*/*/romanNumeral.*
      - archive/*/*/roman_numeral.*
  - base-branch: main
rot13:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/Rot13.*
      - archive/*/*/rot13.*
  - base-branch: main
selection sort:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/SelectionSort.*
      - archive/*/*/selection-sort.*
      - archive/*/*/selectionSort.*
      - archive/*/*/selection_sort.*
  - base-branch: main
sleep sort:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/SleepSort.*
      - archive/*/*/sleep-sort.*
      - archive/*/*/sleepSort.*
      - archive/*/*/sleep_sort.*
  - base-branch: main
transpose matrix:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - archive/*/*/TransposeMatrix.*
      - archive/*/*/transpose-matrix.*
      - archive/*/*/transposeMatrix.*
      - archive/*/*/transpose_matrix.*
  - base-branch: main
