name: Jisho

on:
  push:
    branches: [ main ]

jobs:
  wiki:
    name: "Wiki Generation"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo 
      uses: actions/checkout@v2
      with:
        path: main
        submodules: recursive

    - name: Checkout wiki
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: wiki
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f main/requirements.txt ]; then pip install -r main/requirements.txt; fi
        
    - name: Generate wiki
      run: jisho main/archive --log=DEBUG

    - name: Commit wiki
      continue-on-error: true
      working-directory: ./wiki
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update wiki"
        git push
